### ISSUE TITLE
catalog category page generates error in 3.3.0.8

### ISSUE THREAD

**Issue by jnugent** [pkp/bootstrap3#178] opened 2022-02-15 19:13 UTC
Hi @NateWr 

it looks like the way the `master` branch is checking for subcategories here:

https://github.com/NateWr/bootstrap3/blob/master/templates/frontend/pages/catalogCategory.tpl#L46

Wasn't included in the tagged release for the version of the theme that gets installed via the plugin gallery for 3.3.0.8.  It's still doing:

https://github.com/NateWr/bootstrap3/blob/v3_2_0-4/templates/frontend/pages/catalogCategory.tpl#L46

Which generates a fatal error:

`PHP Fatal error:  Uncaught Error: Call to a member function wasEmpty() on array`

So I think that just needs to be backported back.  I upgraded a client from 3.1.2 to 3.3 today and the theme breaks when it is updated via the gallery.

**Comment by NateWr** [comment] 2022-02-16 10:04
Arg! Yeah it looks like there are a few commits that aren't in the `3_2_0_4` branch. I was planning to make a release after I got confirmation on this bug fix: https://github.com/NateWr/bootstrap3/issues/177.

I can try to sort this out soon. I need to get this set up with the `main`/`stable-x_x_x` branching convention of our other apps.

**Comment by jnugent** [comment] 2022-02-16 12:59
Hi @NateWr if it helps, using the `main` branch for OJS 3.3 seems to resolve the issues.  I found another problem earlier this morning with the `3_2_0_4` branch and 3.3 but that goes away with `main`.

**Comment by kaitlinnewson** [comment] 2024-06-27 14:14
@asmecher This issue can be closed as resolved in https://github.com/pkp/bootstrap3/pull/172 and confirmed in 3.3/3.4/main.

**Comment by asmecher** [comment] 2024-06-27 19:27
Closing, thanks, @kaitlinnewson!

**Closed by asmecher** 2024-06-27 19:27 UTC
Labels: bug
